server {
  listen 80;
  server_name _;

  # Health check (GKE)
  location = / {
    return 200 'ok';
    add_header Content-Type text/plain;
  }

  location = /admin {
    return 301 /admin/;
  }

  # Serve static assets
  location /admin/static/ {
    alias /usr/share/nginx/html/static/;
    try_files $uri =404;
  }

  # Serve CRA under /admin
  location /admin/ {
    alias /usr/share/nginx/html/;
    index index.html;
    try_files $uri $uri/ /admin/index.html;
  }
}
